'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const image = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jB9kAAAAASUVORK5CYII=';
const plan = published => ({ version: 1, image, published, width: 24, depth: 20, height: 10, thickness: .5, scaleConfirmed: true,
  walls: [{ kind: 'wall', a: [.1, .1], b: [.9, .1] }], furniture: [] });

test('upcoming projects retain estimates and models without altering existing homes; auth avoids unused store reads', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'mdu-upcoming-test-'));
  fs.mkdirSync(path.join(dir, 'public'));
  for (const file of ['server.js', 'seo.js', 'public/page-seo.js', 'telegram-bot.js', 'public/floor-plan-geometry.js']) fs.copyFileSync(path.join(__dirname, '..', file), path.join(dir, file));
  for (const key of ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY', 'VERCEL', 'TELEGRAM_BOT_TOKEN']) delete process.env[key];
  process.env.ADMIN_PASSWORD = 'upcoming-test-only';
  const server = require(path.join(dir, 'server.js'));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  let reads = 0;
  const originalRead = fs.readFileSync;
  fs.readFileSync = function (file, ...args) { if (String(file) === path.join(dir, 'data', 'store.json')) ++reads; return originalRead.call(this, file, ...args); };
  t.after(async () => { fs.readFileSync = originalRead; await new Promise(resolve => server.close(resolve)); fs.rmSync(dir, { recursive: true, force: true }); });
  const login = await fetch(base + '/api/login', { method: 'POST', body: JSON.stringify({ password: 'upcoming-test-only' }) });
  assert.equal(login.status, 200); assert.equal(reads, 0, 'login never reads listing storage');
  const cookie = login.headers.get('set-cookie').split(';')[0];
  const call = (url, method = 'GET', body, auth = true) => fetch(base + url, { method, headers: { 'content-type': 'application/json', ...(auth ? { cookie } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  await call('/api/session'); assert.equal(reads, 0, 'session never reads listing storage');
  const before = await (await call('/api/admin/data')).json(); assert.equal(reads, 1, 'dashboard reads storage once');
  const body = { title: 'Vaigai future villas', status: 'upcoming', price: 8200000, location: 'Madurai', expectedCompletion: 'Q4 2027', projectType: 'Independent villas', area: '2,400 sq ft', description: '<p>Planned family homes.</p>', floorPlan: plan(false) };
  assert.equal((await call('/api/admin/listings', 'POST', body, false)).status, 401);
  for (const invalid of [{ price: -1 }, { price: 0 }, { location: '' }, { price: 'invalid' }]) assert.equal((await call('/api/admin/listings', 'POST', { ...body, ...invalid })).status, 400);
  const readsBeforeSave = reads;
  const created = await call('/api/admin/listings', 'POST', body); assert.equal(created.status, 201);
  assert.equal(reads - readsBeforeSave, 1, 'saving reads management storage once');
  const listing = (await created.json()).listing, endpoint = '/api/admin/listings/' + listing.id;
  assert.equal(listing.status, 'upcoming'); assert.equal(listing.price, 8200000); assert.equal(listing.mainImage, '/mark.svg?v=3');
  assert.equal(listing.floorPlan, null, 'private model and source drawing remain private');
  const admin = await (await call('/api/admin/data')).json();
  assert.deepEqual(admin.listings.filter(item => item.id !== listing.id), before.listings, 'existing inventory stays unchanged');
  assert.equal(admin.listings.find(item => item.id === listing.id).floorPlan.image, image);
  const published = await call(endpoint, 'PUT', { floorPlan: plan(true) }); assert.equal(published.status, 200);
  const publicRecord = (await (await call('/api/listings/' + listing.id, 'GET', null, false)).json()).listing;
  assert.equal(publicRecord.expectedCompletion, 'Q4 2027'); assert.equal(publicRecord.projectType, 'Independent villas');
  assert.equal(publicRecord.floorPlan.published, true);
  await call(endpoint, 'PUT', { expectedCompletion: 'Q1 2028', price: 8500000 });
  const revised = (await (await call('/api/listings/' + listing.id)).json()).listing;
  assert.equal(revised.expectedCompletion, 'Q1 2028'); assert.equal(revised.price, 8500000); assert.deepEqual(revised.floorPlan.walls, publicRecord.floorPlan.walls);
  assert.equal((await call(endpoint, 'PUT', { status: 'construction', mainImage: image })).status, 200);
  const started = (await (await call('/api/listings/' + listing.id)).json()).listing;
  assert.equal(started.status, 'construction'); assert.equal(started.floorPlan.published, true);
  await call('/api/logout', 'POST');
});
